name: Build and Deploy to Firebase App Distribution

on:
  push:
    branches:
      - master
      - release/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Check out the repository
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17 (Corretto)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      # Step 3: Decode and save google-services.json
      - name: Decode google-services.json
        run: echo ${{ secrets.GOOGLE_SERVICES_JSON }} | base64 --decode > $GITHUB_WORKSPACE/app/google-services.json

      # Step 3.1: Decode and save config
      - name: Decode config.properties
        run: echo ${{ secrets.CONFIG_PROPERTIES }} | base64 --decode > $GITHUB_WORKSPACE/config.properties

      # Step 4: Set up Gradle
      - name: Cache Gradle files
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Step 5: Build APK using Gradle 8
      - name: Build release APK
        run: ./gradlew assembleRelease --no-daemon

      # Step 6: Upload to Firebase App Distribution
      - name: Deploy to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: 'tester'
          file: app/build/outputs/apk/release/app-release.apk
